
package com.cfcc.cap.ws.creditscore;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSWebService", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", wsdlLocation = "http://172.18.6.61:8082/PLATFORMWS/zzfw-ws/ws?wsdl")
public class WSWebService_Service
    extends Service
{

    private final static URL WSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSWEBSERVICE_EXCEPTION;
    private final static QName WSWEBSERVICE_QNAME = new QName("http://creditscore.ws.cap.cfcc.com/", "WSWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.18.6.61:8082/PLATFORMWS/zzfw-ws/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSWEBSERVICE_WSDL_LOCATION = url;
        WSWEBSERVICE_EXCEPTION = e;
    }

    public WSWebService_Service() {
        super(__getWsdlLocation(), WSWEBSERVICE_QNAME);
    }

    public WSWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSWEBSERVICE_QNAME, features);
    }

    public WSWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, WSWEBSERVICE_QNAME);
    }

    public WSWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSWEBSERVICE_QNAME, features);
    }

    public WSWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSWebService
     */
    @WebEndpoint(name = "WSWebServiceImplPort")
    public WSWebService getWSWebServiceImplPort() {
        return super.getPort(new QName("http://creditscore.ws.cap.cfcc.com/", "WSWebServiceImplPort"), WSWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSWebService
     */
    @WebEndpoint(name = "WSWebServiceImplPort")
    public WSWebService getWSWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://creditscore.ws.cap.cfcc.com/", "WSWebServiceImplPort"), WSWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSWEBSERVICE_EXCEPTION!= null) {
            throw WSWEBSERVICE_EXCEPTION;
        }
        return WSWEBSERVICE_WSDL_LOCATION;
    }

}
