
package com.cfcc.cap.ws.creditscore;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSWebService", targetNamespace = "http://creditscore.ws.cap.cfcc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreCards", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreCards")
    @ResponseWrapper(localName = "getScoreCardsResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreCardsResponse")
    public String getScoreCards(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMenus", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetMenus")
    @ResponseWrapper(localName = "getMenusResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetMenusResponse")
    public String getMenus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreInfoNew", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreInfoNew")
    @ResponseWrapper(localName = "getScoreInfoNewResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreInfoNewResponse")
    public String getScoreInfoNew(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatusNew", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetStatusNew")
    @ResponseWrapper(localName = "getStatusNewResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetStatusNewResponse")
    public String getStatusNew(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCorps", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetCorps")
    @ResponseWrapper(localName = "getCorpsResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetCorpsResponse")
    public String getCorps(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreInfos", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreInfos")
    @ResponseWrapper(localName = "getScoreInfosResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreInfosResponse")
    public String getScoreInfos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCorpInfos", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetCorpInfos")
    @ResponseWrapper(localName = "getCorpInfosResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetCorpInfosResponse")
    public String getCorpInfos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCorpsNew", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetCorpsNew")
    @ResponseWrapper(localName = "getCorpsNewResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetCorpsNewResponse")
    public String getCorpsNew(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreInfo", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreInfo")
    @ResponseWrapper(localName = "getScoreInfoResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreInfoResponse")
    public String getScoreInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMenusNew", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetMenusNew")
    @ResponseWrapper(localName = "getMenusNewResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetMenusNewResponse")
    public String getMenusNew(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreCardsNew", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreCardsNew")
    @ResponseWrapper(localName = "getScoreCardsNewResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetScoreCardsNewResponse")
    public String getScoreCardsNew(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://creditscore.ws.cap.cfcc.com/", className = "com.cfcc.cap.ws.creditscore.GetStatusResponse")
    public String getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
